// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkjzwrkubeztdyryciw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a2p6d3JrdWJlenRkeXJ5Y2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzA0MTksImV4cCI6MjA2NTkwNjQxOX0.6sHh3bi0ne4N5-Chgcl0h4-a3RZuKlRUbvmwnSsyY_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);